version: "3.7"
services:
  web:
    container_name: gpt2zh-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:?\nPlease set the PORT variable}:8000"
    volumes:
      - type: bind
        source: "${MODELDIR:?\nPlease set the MODELDIR variable}"
        target: /gpt2zh/models
